// bench/bundle-size/solid/src/App.tsx
import { createSignal } from "solid-js";

function App() {
  const [count, setCount] = createSignal(0);

  return (
    <div>
      <h1>Bench Counter</h1>
      <h3>{count()}</h3>
      <button type="button" onClick={() => setCount(count() + 1)}>
        add
      </button>
    </div>
  );
}

export default App;

// bench/bundle-size/preact/src/App.tsx
import { useState } from "preact/hooks";

function App() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>Bench Counter</h1>
      <h3>{count}</h3>
      <button type="button" onClick={() => setCount(count + 1)}>
        add
      </button>
    </div>
  );
}

export default App;
